version: '3.5'
services:
  gateway:
    image: gateway-service:latest
    ports:
      - "8080:8080"
    depends_on:
      - discovery
  
  img:
    image: image-service:latest
    ports:
      - 8082:8082
    depends_on:
      - imagedb
      - discovery
    command: ["./image-service", "--host=img", "--docker=true"]
  
  analys:
    image: analytics-service:latest
    ports:
      - "8083:8083"
    depends_on:
      - img
      - discovery
      - analyticsdb
    command: ["./analytics-service", "--host=analys", "--docker=true"]
  
  discovery:
    image: discovery-service:latest
    ports:
      - "8500:8500"
  
  imagedb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=mongopassword
    ports:
      - "27017:27017"
    volumes:
      - ./local/db-data/mongo-data:/data/mongo
  
  analyticsdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: ANALYTICSDB
      POSTGRES_PASSWORD: postpass
    ports:
      - 5432:5432
    volumes:
      - ./local/db-data/postgres-analytics-data:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./local/db-data/redis-db:/data/redis
  
  userdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: USERDATABASE
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - 5433:5432
    volumes:
      - ./local/db-data/postgres-user-data:/var/lib/postgresql/data