# Gemfile
source "https://rubygems.org"

# Web framework
gem 'sinatra'
gem 'puma'
gem 'http'
gem 'faraday'


# redis
gem 'redis'

#env
gem 'dotenv'
gem "multipart-post", "~> 2.3"

gem "httparty", "~> 0.21.0"
