# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/auth_svc.proto for package ''

require 'grpc'
require 'proto/auth_svc_pb'

module AuthService
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'AuthService'

    rpc :Login, ::LoginRequest, ::LoginResponse
    rpc :Register, ::RegisterRequest, ::RegisterResponse
    rpc :RefreshToken, ::RefreshRequest, ::RefreshResponse
    rpc :Delete, ::DeleteRequest, ::DeleteResponse
    rpc :GetAll, ::Google::Protobuf::Empty, ::GetAllResponse
    rpc :DeleteAll, ::Google::Protobuf::Empty, ::DeleteAllResponse
  end

  Stub = Service.rpc_stub_class
end
