# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: image_svc.proto for package ''

require 'grpc'
require 'image_svc_pb'

module ImageService
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'ImageService'

    rpc :GetImage, ::GetImageRequest, ::GetImageResponse
    rpc :UploadImage, ::UploadImageRequest, ::UploadImageResponse
    rpc :DeleteImage, ::DeleteImageRequest, ::DeleteImageResponse
    rpc :ModifyImage, ::ModifyImageRequest, ::ModifyImageResponse
    rpc :GetImageList, ::GetImageListRequest, ::GetImageListResponse
  end

  Stub = Service.rpc_stub_class
end
