# Use the official Go image as a base image
FROM golang:1.21.0-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the local package files to the container's workspace
COPY . .

# Download and install any dependencies your application needs
RUN go mod download

# Build the Go application
RUN go build -o image-service

# Expose the port that the application will run on
EXPOSE 8082

# Command to run the executable
CMD ["./image-service"]
